Allow discovery search results to be sorted
Stanford-Online/edx-search pull request #2
Opened 2019-03-08 21:47 UTC by kluo

@stvstnfrd

2019-03-08 21:49 UTC, stvstnfrd requested changes

2019-03-08 21:49 UTC, stvstnfrd commented on search/api.py
> +        sort=getattr(settings, 'SEARCH_DISCOVERY_SORT_FIELDS', ''),
Is empty string the same as passing no string?

2019-03-08 21:49 UTC, stvstnfrd commented on setup.py
> +    version='1.2.2',
Maybe this should be a minor version bump?
It's not really a bug fix; it's a backward-compatible feature improvement :)

2019-03-08 21:50 UTC, stvstnfrd commented
We should definitely send this upstream asap!

2019-03-09 00:29 UTC, kluo commented on search/api.py
> +        sort=getattr(settings, 'SEARCH_DISCOVERY_SORT_FIELDS', ''),
Correct

2019-03-09 01:14 UTC, stvstnfrd approved these changes

2019-03-09 01:17 UTC, stvstnfrd commented
Can you lob this over to edx?

Hopefully this will be an easy win 🤞

2019-03-09 01:23 UTC, merged